apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticketting-expiration-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticketting-expiration
  template:
    metadata:
      labels:
        app: ticketting-expiration
    spec:
      containers:
        - name: ticketting-expiration
          image: mydevlab:5000/ticketting-expiration
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL 
              value: 'http://ticketting-nats-service:4222'
            - name: NATS_CLUSTER_ID
              value: 'ticketting'
            - name: REDIS_HOST
              value: 'ticketting-expiration-redis-service'
            